In [3]:
import numpy as np

Numpy

Задание 1

In [72]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])

In [73]:
a = a.T

In [74]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [92]:
mean_a = np.mean(a, axis = 0, dtype=np.float64)

In [93]:
mean_a

array([2. , 8.4])

Задание 2

In [95]:
a_centered = a - mean_a

In [96]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [108]:
a_centered = a_centered.T

In [113]:
a_c = a_centered[0]*a_centered[1]
a_c

array([ 2.4, -0. ,  2.6,  1.6,  1.4])

In [115]:
a_cov = sum(a_centered[0]*a_centered[1]) / (a_c.size - 1)
a_cov

2.0

Задание 4

In [122]:
a = a.T

In [123]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [124]:
np.cov(a)

array([[1. , 2. ],
       [2. , 4.3]])

Pandas

Задание 1

In [125]:
import pandas as pd

In [152]:
authors = {'author_id': [1, 2, 3], 'author_name':['Тургенев', 'Чехов', 'Островский']}

In [153]:
authors  = pd.DataFrame(authors )
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [146]:
book = {
    'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]
}

In [148]:
book = pd.DataFrame(book)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [149]:
book.describe()

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000

In [156]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

In [157]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [158]:
authors_price.sort_values(by="price", inplace=True)

In [159]:
authors_price

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
3          2       Чехов      Толстый и тонкий    500

In [160]:
top5 = authors_price.tail(5)

In [161]:
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [162]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [163]:
authors_price["author_name"].unique()

array(['Островский', 'Тургенев', 'Чехов'], dtype=object)

In [177]:
authors_stat = authors_price.groupby("author_name").agg({"price": "min"})

In [175]:
authors_stat

price
author_name       
Островский     290
Тургенев       300
Чехов          450

In [178]:
authors_stat = authors_stat.rename(columns={'price': 'min_price'})

In [179]:
authors_stat

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [180]:
authors_stat1 = authors_price.groupby("author_name").agg({"price": "max"})

In [181]:
authors_stat1

price
author_name       
Островский     370
Тургенев       450
Чехов          500

In [182]:
authors_stat1 = authors_stat1.rename(columns={'price': 'max_price'})

In [184]:
authors_stat2 = authors_price.groupby("author_name").agg({"price": "mean"})

In [185]:
authors_stat2 = authors_stat2.rename(columns={'price': 'mean_price'})

In [193]:
authors_stat = pd.concat([authors_stat, authors_stat1, authors_stat2], axis=1)

In [194]:
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000